version: '3.8'

services:
  web:
    build: .
    volumes:
      - web-data:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - db

  ftp:
    image: fauria/vsftpd
    restart: always
    environment:
      FTP_USER: user
      FTP_PASS: password
    volumes:
      - web-data:/home/vsftpd
    ports:
      - "210:210"
      - "8888-8889:8888-8889"
    depends_on:
      - web

volumes:
  web-data:
  db-data:
