# Utiliser une image de base pour PHP avec FPM et Nginx
FROM php:8.1-fpm

# Installer Nginx et des extensions PHP nécessaires
RUN apt-get update && apt-get install -y nginx && \
    docker-php-ext-install pdo pdo_mysql

# Configurer Nginx
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copier le fichier de configuration de PHP-FPM
COPY ./www.conf /usr/local/etc/php-fpm.d/www.conf

# Copier les fichiers du site web
COPY ./public /var/www/html

# Exposer les ports nécessaires
EXPOSE 80

# Démarrer PHP-FPM et Nginx
CMD ["sh", "-c", "php-fpm -D && nginx -g 'daemon off;'"]
